; Fern syntax highlighting for Tree-sitter
; AUTO-GENERATED by scripts/generate_editor_support.py
; Do not edit manually - run 'just editor-support' to regenerate

; =============================================================================
; Keywords
; =============================================================================

; All keywords
[
  "after"
  "and"
  "as"
  "break"
  "continue"
  "defer"
  "derive"
  "do"
  "else"
  "fn"
  "for"
  "if"
  "impl"
  "import"
  "in"
  "let"
  "match"
  "module"
  "newtype"
  "not"
  "or"
  "pub"
  "receive"
  "return"
  "send"
  "spawn"
  "trait"
  "type"
  "where"
  "with"
] @keyword

; Control flow keywords
[
  "break"
  "continue"
  "else"
  "for"
  "if"
  "match"
  "return"
  "with"
] @keyword.control

; Storage/declaration keywords
[
  "fn"
  "impl"
  "let"
  "newtype"
  "trait"
  "type"
] @keyword.storage

; Visibility
[
  "pub"
] @keyword.modifier

; =============================================================================
; Operators
; =============================================================================

[
  "!="
  "%"
  "*"
  "**"
  "+"
  "-"
  "->"
  "/"
  "<"
  "<-"
  "<="
  "="
  "=="
  "=>"
  ">"
  ">="
  "?"
  "|"
  "|>"
] @operator

; Logical operators (also keywords)
[
  "and"
  "or"
  "not"
] @keyword.operator

; Pipe operator (special highlight)
"|>" @operator

; Question mark operator
"?" @operator

; =============================================================================
; Punctuation
; =============================================================================

; Delimiters
[
  ","
  "."
  ".."
  "..."
  "..="
  ":"
  "@"
] @punctuation.delimiter

; Brackets
[
  "("
  ")"
  "["
  "]"
  "{"
  "}"
] @punctuation.bracket

; =============================================================================
; Types
; =============================================================================

; Built-in types
[
  "Bool"
  "Float"
  "Int"
  "List"
  "Map"
  "Option"
  "Result"
  "String"
] @type.builtin

; Type constructors (capitalized identifiers)
((identifier) @type
  (#match? @type "^[A-Z][A-Za-z0-9_]*$"))

; =============================================================================
; Literals
; =============================================================================

; Boolean literals
[
  "false"
  "true"
] @constant.builtin.boolean

; Result/Option constructors
[
  "Err"
  "None"
  "Ok"
  "Some"
] @constructor

; Numeric literals
(integer_literal) @constant.numeric.integer
(float_literal) @constant.numeric.float

; String literals
(string_literal) @string
(interpolated_string) @string
(string_interpolation) @embedded

; =============================================================================
; Comments
; =============================================================================

(line_comment) @comment.line
(block_comment) @comment.block
(doc_comment) @comment.documentation

; =============================================================================
; Functions
; =============================================================================

; Function definitions
(function_definition
  name: (identifier) @function)

; Function calls
(call_expression
  function: (identifier) @function.call)

; Method calls (after dot)
(method_call
  method: (identifier) @function.method)

; =============================================================================
; Variables and Parameters
; =============================================================================

; Parameters in function definitions
(parameter
  name: (identifier) @variable.parameter)

; Generic identifiers (fallback)
(identifier) @variable

; Wildcard pattern
"_" @constant.builtin

; =============================================================================
; Other
; =============================================================================

; Attributes (@doc, etc.)
(attribute) @attribute

; Module paths
(module_path) @module
