#!/usr/bin/env bash
# Ralph Loop - Overnight Runner
#
# Runs Ralph Loop continuously by invoking new Claude Code sessions

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║         Ralph Loop - Overnight Mode                      ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "This script helps you run Ralph Loop overnight."
echo ""
echo "⚠️  Important Setup Required:"
echo ""
echo "1. The Ralph Loop needs manual iteration for now because:"
echo "   - Claude Code doesn't have an API/CLI mode yet"
echo "   - Each iteration needs a new session"
echo "   - Tasks need human judgment"
echo ""
echo "2. For semi-automated workflow:"
echo ""
echo "   MORNING:"
echo "   - I act as CONTROLLER: verify last night's work"
echo "   - Select next task, set Agent Turn: IMPLEMENTER"
echo "   - Git push"
echo ""
echo "   EVENING:"
echo "   - You open Claude Code"
echo "   - Say: \"Act as IMPLEMENTER, complete current task from ROADMAP.md\""
echo "   - Claude implements (RED → GREEN)"
echo "   - Updates ROADMAP.md, sets Agent Turn: CONTROLLER"
echo "   - Git commit & push"
echo ""
echo "   REPEAT: Next morning, CONTROLLER verifies..."
echo ""
echo "3. For fully automated (future):"
echo "   - Wait for Claude Code CLI/API support"
echo "   - Then this script can invoke sessions automatically"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Current Workaround:"
echo ""
echo "Option A: Stay in this session"
echo "  - I can continue implementing as IMPLEMENTER"
echo "  - Complete multiple tasks tonight"
echo "  - You review in the morning"
echo ""
echo "Option B: Come back tomorrow"
echo "  - I act as CONTROLLER now (verify if expressions)"
echo "  - Select next task for tomorrow"
echo "  - You implement tomorrow evening"
echo ""
echo "Option C: Manual iterations"
echo "  - Run: ./scripts/ralph-iteration.sh"
echo "  - Follow prompts for each agent"
echo "  - Repeat as many times as you want"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Which would you like?"
echo ""
echo "  1) Continue in this session (I implement more features)"
echo "  2) I act as CONTROLLER and set up tomorrow's task"
echo "  3) Show me how to do it manually"
echo ""
echo "Or Ctrl+C to stop and think about it."
echo ""
